server:
  port: 9002

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400