server:
  port: 9297

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rajatkumar012/monitoring-cloud-config.git
          clone-on-start: true

